spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@100.100.100.159:1521:orcl
      username: insurance
      password: insurancedba
      filters: encoding
      connection-properties: serverEncoding=ISO-8859-1;clientEncoding=GBK

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl